[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = "0.5"
rocket_cors = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rocket_okapi = { version = "0.9.0", features = ["swagger"]}